name: flutter_screenshot_google_street_view
description: A Flutter package for capturing Google Street View screenshots
version: 0.0.1
homepage: https://github.com/lualbertovargas/flutter_screenshot_google_street_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_google_street_view: ^3.1.4
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
